# Generated by Django 3.0.6 on 2020-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoDatabase',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
