# Generated by Django 3.0.6 on 2020-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200605_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododatabase',
            name='slug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
